main.tf

This tag causes arm templates to be applied when they don't need to be, confirmed with Dan it is not needed
```
[ ] Yes
[ ] No
```

Remove unneeded tag

---

main.tf
variables.tf

Jenkins library does team name automatically now
https://github.com/hmcts/cnp-jenkins-library/blob/master/src/uk/gov/hmcts/contino/TeamNames.groovy

Remove unneeded var

---

docker-compose.yml

Map PostgreSQL port to a non-default one so that people can still run PostgreSQL on their host machines.
```
[ ] Yes
[x] No
```

Map PostgreSQL port to a non-default one

---

docker-compose.yml

Docker volumes config was added to "ccd-case-management-web" instead of "ccd importer" service in the docker-compose file. 
Moved it to the ccd-importer service config
```
[ ] Yes
[ x] No
```

Added docker volumes to ccd-importer service in docker-compose file

---

queue.tf

Since https://github.com/hmcts/terraform-module-servicebus-queue/pull/2 has been merged the existing state of the queue started to fail on new builds. Rename should force rebuild and hopefully solve the non-passing build which is happening since #49
```
[ ] Yes
[x] No
```

Force terraform state change for the existing queue module

---

queue.tf

Increase message lock duration in the queues, so that if there's a problem with a dependency, the messages will stay in the main queue for at lease 50 minutes, before eventually being dead-lettered.
```
[ ] Yes
[x] No
```

Increase message lock duration in the queues

---

no-envelopes-processed-alert.tf

[No envelopes processed alert](https://tools.hmcts.net/jira/browse/BPS-541)
This is based on log entry made by blob processor task in [Bulk Scan Processor](https://github.com/hmcts/bulk-scan-processor).
As per ticket instructions:
- considered interval is last hour
- SLA is 9am - 5pm, so query considers that and only starts alerting from 10am as it makes one hour only then
- weekends are excluded in this initial version
```
[ ] Yes
[x] No
```

Add new alert for no envelopes processed

---

exception-alert.tf

After initial run we inspected the differences and realised the alert must also include traces and everything wrapped with severity of level 3
```
[ ] Yes
[x] No
```

Update exception alert

---

no-envelopes-processed-alert.tf

[No envelopes processed alert](https://tools.hmcts.net/jira/browse/BPS-541)
Cause:
Whenever PR is merged and Jenkins build picks up the event upon completion alert is registered to kick off from `last updated + frequency`. Therefore alert can check window which is too early or too late. First option can cause the alert, second - will not. In both cases windows are not within SLA
Solution:
Strictly bound range to be exactly of module of an hour. This change assures window checks from 0900-1000 to 1600-1700
Summary:
After running the following:
```mql5
let range_end = bin(now(), 1h);
traces
| where timestamp > ago(2h)
| where message startswith "Processing zip file"
| make-series count(message) default=0 on timestamp in range(range_end - 1h, range_end, 1m)
| mvexpand count_message, …
```

Force window to be within one hour starting from HH:00

---

storage-account.tf

Flag for `sensitivity` must be boolean. This must have been derived from template validation rather than terraform types themselves
```
[ ] Yes
[x] No
```

Make flag bool

---

key-vault.tf
main.tf
storage-account.tf

Bring configuration to the state before Key Vault module change:
* azurerm version 1.19.0
* referencing the older version of cnp-module-key-vault module
```
[ ] Yes
[x] No
```

Bring configuration to the state before Key Vault module change

---

exception-alert.tf
liveness-alert.tf
no-envelopes-processed-alert.tf

-  This PR is to test if the enabled field in alert module is causing terraform to initialise the backend.
```
[ ] Yes
[x ] No
```

Enable alerts on demo

---

alert_action_group.tf
key-vault.tf
prod.tfvars
queue.tf
storage-account.tf
variables.tf

https://tools.hmcts.net/jira/browse/BPS-599
Store Service Bus connection strings and Storage Account secrets in Vault, so that the services' Terraform can access that information without having to rely on shared infrastructure's state file.
DO NOT MERGE - can only be merged after SIDAM go-live.
```
[ ] Yes
[x] No
```

Store Service Bus connection strings and Storage Account secrets in Vault

---

app-gateway.tf

- Working build on sandbox : https://sandbox-build.platform.hmcts.net/job/HMCTS_Sandbox_Platform/job/bulk-scan-shared-infrastructure/job/FIX-VAULT-NAME/
- Someone with prod access will need to check if the certs are available in resource group/vault name
```
[ ] Yes
[ x] No
```

Fixed vault name based on subscription

---

aat.tfvars
key-vault.tf
variables.tf

-  Currently `bulk-scan-payment-processor` master build is broken on AAT as the managed identity config for key vault is missing. This PR addresses that issue.
```
[ ] Yes
[ x] No
```

Added managed identity obj id to access AAT vault

---

application-insights.tf

https://tools.hmcts.net/jira/browse/BPS-841
- Added config to set app insights key into bulk scan vault.
- This will be later used in bulk scan processor chart which will is needed for the app. Other way is to do this was to configure in flux as an env var but that was not recommended approach.
```
[ ] Yes
[ x] No
```

Added resource to set app insights instrumentation key to vault

---

palo-alto.tf

- Currently build fails while activating the virtual environment with error 
```venv/bin/activate no such file or directory```.
- This is an attempt to see if that fixes the issue. Changes in Palo Alto repo are merged as it may impact other consumers of the module. Hence testing by referring to branch that contains upgrade changes.
```
[ ] Yes
[ x] No
```

Used pip upgrade branch to upgrade pip

---

Jenkinsfile_CNP

- Temporarily disable prod deployment as it causes a downtime to our supplier due to manual changes being applied to our infrastructure.
- This PR allows devs to merge to master which deploys infra changes to non prod environment thereby unblocking piling up of infra PR's.
- Also this way we can test our changes in non prod environment but also brings a bit risk that when we remove this lot of changes may be applied to prod infrastructure.
```
[ ] Yes
[ x] No
```

Mark the build as successful after AAT deployment

---

Jenkinsfile_CNP

Continuing from https://github.com/hmcts/bulk-scan-shared-infrastructure/pull/172 looks like we need to break the pipeline deliberately otherwise it just continues with prod deployment.
```
[ ] Yes
[ x] No
```

Halt before prod deployment

---

main.tf
queue.tf

This seems to be mandatory now, PRs are failing with:
```
Error: module.queue-namespace.azurerm_template_deployment.namespace: 1 error(s) occurred:
* module.queue-namespace.azurerm_template_deployment.namespace: lookup: lookup failed to find 'Team Name' in:
${lookup(var.common_tags, "Team Name")}

Add team name

---

palo-alto-staging.tf
palo-alto.tf

* Previous pip upgrade branch changes have been merged to master now 
* `add-pdf-threat-exclusion` includes adding exclusion for PDF threat id 34805 https://github.com/hmcts/cnp-module-palo-alto/tree/add-pdf-threat-exclusion
More details are included here https://tools.hmcts.net/jira/browse/BPS-1117
* This exclusion is currently applied by Devops manually on palo instances so it is currently in prod and being approved by IA.
* We can't merge the exclusion change to master as it will apply to all the consumers of palo module.
* Also soon we are migrating to shared Palos so this should be just an interim solution.

Refer to branch of palo module containing pdf threat exclusion

---

storage-account-staging.tf
storage-account.tf

Please see https://tools.hmcts.net/jira/browse/DTSPO-5553
This is step 1 of 2 in the Storage HA work in progress.
In order for Storage to use high availability we need to use a v2 account, currently this is using a v1 because of how it was setup.
This will be migrated in the background using an Azure migration process and then terraform ran afterwards to refresh the state

DTSPO-5553 Switch to v2 storage

---

queue-premium.tf
state.tf

The `zoneRedundant` variable has been update to `zone_redundant` to follow the correct way to name variables in terraform 
https://www.terraform-best-practices.com/naming#general-conventions
```
[ ] Yes
[x] No
```

Update zoneRedundant variable to zone_redundant

---

provider.tf
queue-premium.tf
queue.tf

https://tools.hmcts.net/jira/browse/DTSPO-6371
PlatOps have made some changes to the service bus terraform module, mainly around adding the ability to enable private endpoints. We needed to add a Private Endpoint provider to allow for Private endpoints being deployed to a different Subscription to the Service Bus being created. 
This change should have no effect on anything currently deployed, but it will allow you to deploy a Service Bus with a Private Endpoint if you add the correct inputs to the module. 
More information on that can be found here: https://github.com/hmcts/terraform-module-servicebus-namespace#usage
```
[ ] Yes
[x] No
```

DTSPO-6371 add private endpoint provider for service bus

---

application-insights.tf
dead-letter.tf
dlq-alert.tf
exception-alert.tf
heartbeat-alert.tf
incomplete-envelopes-alert.tf
liveness-alert.tf
no-new-envelopes-alert.tf
orchestrator-scheduled-jobs-alerts.tf
payments-scheduled-jobs-alerts.tf
processor-scheduled-jobs-alerts.tf

Jira link (if applicable)
https://tools.hmcts.net/jira/browse/DTSPO-15909
Change description
Updating azurerm_application_insights resource and replacing it with module terraform-module-application-insights
This will allow us to migrate Classic Application Insights using https://github.com/hmcts/app-insights-migration-tool as Classic Application Insights will deprecated and will be retired in February 2024.

DTSPO-15909 - migrating app insights to workspace based.
