hmcts/bulk-scan-shared-infrastructure

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- LICENSE.md
https://tools.hmcts.net/jira/browse/RPE-680
Add github files
```
[ ] Yes
[ x ] No
```
> RPE-680 Add github files and license

- state.tf
Without this state wasn't being stored
```
[ ] Yes
[ ] No
```
> RPE-680 Add state storage

- queue.tf
https://tools.hmcts.net/jira/browse/RPE-680
Need to output anything we want to access from shared remote state
> Output primary listen string

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RPE-680
No point running preview on master, it gets deleted every day so every time you'll have to wait to re-create it, useful for PRs though
```
[ ] Yes
[ ] No
```
> RPE-680 Remove preview from onMaster

- queue.tf
Add send queue to output.
```
[ ] Yes
[x] No
```
> Add send queue to output.

- docker-compose.yml
https://tools.hmcts.net/jira/browse/RPE-714
Add client config
```
[ ] Yes
[x] No
```
> RPE-714 Add client configuration needed for auth

- docker-compose.yml
typo in the config
```
[ ] Yes
[ ] No
```
> Fix user config

- asp.tf
We shouldn't need the number of workers that we had before, let's try this out and increase it if we need
> Downsize the number of workers in a plan

- docker/ccd-definition-import/Dockerfile
- docker/ccd-definition-import/scripts/upload-definition.sh
Skip temp files that make the script blow up and copy files properly
```
[ ] Yes
[ ] No
```
> Fix spreadsheet upload script

- Jenkinsfile_CNP
- Jenkinsfile_parameterized
- storage-account.tf
https://tools.hmcts.net/jira/browse/RPE-752
These vars are needed in processor,
also jenkins-library branch is now merged so back to master for it
```
[ ] Yes
[ ] No
```
> RPE-752 Output vars needed by processor

- storage-account.tf
https://tools.hmcts.net/jira/browse/RPE-725
Testing creating new container with DNS not pointing to blob storage
```
[ ] Yes
[ ] No
```
> Add divorce storage container

- README.md
- docker-compose.yml
https://tools.hmcts.net/jira/browse/RPE-755
Fixed dm-store to work in local
```
[ ] Yes
[ x] No
```
> RPE-755 Fixed document management setup

- storage-account.tf
https://tools.hmcts.net/jira/browse/RPE-679
Add service-specific 'rejected' containers. Also, create containers in a more dynamic way.
```
[ ] Yes
[x] No
```
> Add service-specific 'rejected' containers

- queue.tf
Jira: https://tools.hmcts.net/jira/browse/RPE-682
> Enable 1h duplicate detection

- application-insights.tf
- queue.tf
https://tools.hmcts.net/jira/browse/RPE-824
Fix missing common_tags issue.
```
[ ] Yes
[x] No
```
> Add common tags

- docker/ccd-definition-import/data/.gitignore
- docker/ccd-definition-import/scripts/add-ccd-role.sh
- docker/ccd-definition-import/scripts/create-importer-user.sh
- docker/ccd-definition-import/scripts/import-definition.sh
- docker/ccd-definition-import/scripts/template_ccd_definition.py
Several different changes here.
Open to suggestions.
> CCD import scripts cleanup

- queue.tf
[Create new queue for notification messages](https://tools.hmcts.net/jira/browse/BPS-189)
Mimicking the `queue` module and output
```
[ ] Yes
[x] No
```
> Create queue for notifications

- queue.tf
- add `envelopes` prefix to old queue (`queue_primary_listen_connection_string`)
- add `queue` to `notification_primary_send_connection_string`
> Nicer output var names

- .gitignore
- docker-compose.yml
- docker/ccd-definition-import/scripts/idam-authenticate.sh
- docker/ccd-definition-import/scripts/upload-definition.sh
https://tools.hmcts.net/jira/browse/RPE-874
Move all ccd importer parameters to environment variables that can be passed from docker file (or kubernetes definition at some point).
```
[ ] Yes
[x] No
```
> Importer env

- main.tf
locking versions so we can build in sandbox.
> locked the azurerm version.

- app-gateway.tf
- state.tf
> Jj appgw own subnet

- queue.tf
https://tools.hmcts.net/jira/browse/BPS-452
Create a queue for notifying the processor of envelopes that have been processed, i.e. the right action has successfully been done in CCD.
```
[ ] Yes
[x] No
```
> Create queue for notifying of processed envelopes

- app-gateway.tf
Provide common_tags for appGw module. It's required now.
```
[ ] Yes
[x] No
```
> Provide common_tags for appGw module

- alert_action_group.tf
- liveness-alert.tf
[Create alerts for application errors](https://tools.hmcts.net/jira/browse/BPS-550)
Depends on https://github.com/hmcts/cnp-module-metric-alert/pull/6
As part of initial alerting set up common action group is included in this PR. Vault check:
```bash
$ ./bin/check-all-vaults.sh bulk-scan-alert-email
Max retries exceeded attempting to connect to vault. The vault may not exist or you may need to flush your DNS cache and try again later.
ERROR: Didn't find secret bulk-scan-alert-email in environment sandbox
INFO: Found secret bulk-scan-alert-email in environment saat
INFO: Found secret bulk-scan-alert-email in environment sprod
INFO: Found secret bulk-scan-alert-email in environment demo
Max retries exceeded attempting to connect to vault. The vault may not exist or you may need to flush …
```
> Feature: health check monitoring

- app-gateway.tf
- queue.tf
https://tools.hmcts.net/jira/browse/BPS-488
Increased envelopes queue message lock duration to 10 minutes and 
max delivery count to 144 (24*6)
```
[ ] Yes
[ ] No
```
> BPS-488 Update envelopes queue config

- exception-alert.tf
- liveness-alert.tf
[Create alert for application errors](https://tools.hmcts.net/jira/browse/BPS-550)
Single alert for any exception.
Extras:
- liveness severity is not **that** high really
- changing liveness alert source to master branch
Next actions:
- move alert related code to folder so it's collected in one place disregarding how many alerts we have + they will be exec'ed after root terraform applied. win win
```
[ ] Yes
[x] No
```
> Feature: exception monitoring

- exception-alert.tf
[Create alerts for application errors](https://tools.hmcts.net/jira/browse/BPS-550)
Looks like azure doesn't support custom value for timeframes
```
[ ] Yes
[x] No
```
> Fix exception alert

- exception-alert.tf
First step in order to figure out the problem of now alerts
```
[ ] Yes
[x] No
```
> Temporary enable alerts on aat

- exception-alert.tf
Reverts hmcts/bulk-scan-shared-infrastructure#73
Not needed anymore
> Revert "Temporary enable alerts on aat"

- storage-account.tf
> Add FinRem container

- no-envelopes-processed-alert.tf
[No envelopes processed alert](https://tools.hmcts.net/jira/browse/BPS-541)
```
[ ] Yes
[x] No
```
> Fix weekend condition

- prod.tfvars
- queue.tf
- variables.tf
[DLQ Notification](https://tools.hmcts.net/jira/browse/BPS-532)
Wait for hmcts/bulk-scan-processor#555 **master build pass before merging this**. Then kick off this one and revert the hmcts/bulk-scan-processor#555 changes
```
[ ] Yes
[x] No
```
> Output delivery count of envelope queue

- main.tf
Upgrade azurerm provider to version 1.22.1, for consistency across Bulk Scan.
```
[ ] Yes
[x] No
```
> Upgrade azurerm provider to version 1.22.1

- key-vault.tf
Provide common_tags in vault module. It's required now.
```
[ ] Yes
[x] No
```
> Provide common_tags in vault module

- storage-account.tf
Couple places had Bool values. Terraform does not interpret them correctly (especially "false" intended ones). This PR does not hurt broken pipeline as it is - merely addresses the error message
```
[ ] Yes
[x] No
```
> Fix tf files

- key-vault.tf
Reverts hmcts/bulk-scan-shared-infrastructure#87
> Revert "Use a previous branch of key vault"

- main.tf
Require exact version of azurerm provider
```
[ ] Yes
[x] No
```
> Require exact version of azurerm provider

- storage-account.tf
Set azurerm version to 1.22.1 in storage account
```
[ ] Yes
[x] No
```
> Set azurerm version to 1.22.1 in storage account

- exception-alert.tf
- liveness-alert.tf
- no-envelopes-processed-alert.tf
Reverts hmcts/bulk-scan-shared-infrastructure#92
> Revert "Enable alerts on demo"

- dlq-alert.tf
[DLQ Notification](https://tools.hmcts.net/jira/browse/BPS-532)
Alert for dead letter events
```
[ ] Yes
[x] No
```
> Add dead letter alert

- dlq-alert.tf
[DLQ Notification](https://tools.hmcts.net/jira/browse/BPS-532)
2 issues:
- forgot to amend module name after copy/paste
- after comment to do nonprod i suspect alert name must have a different name - appending env var
```
[ ] Yes
[x] No
```
> Fix DLQ alert

- alert_action_group.tf
Changed email in aat vault. Need some change in action group to reflect that. If we're happy can update email in all vaults and revert this change. Because we are aiming to prod only alerts
```
[ ] Yes
[X] No
```
> Temporary change action group name

- dlq-alert.tf
[DLQ Notification](https://tools.hmcts.net/jira/browse/BPS-532)
Switch to prod + nice to have delivery counter ready for you to use
```
[ ] Yes
[x] No
```
> Switch alert to prod

- storage-account.tf
https://tools.hmcts.net/jira/browse/BPS-616
> Add storage container for cmc

- exception-alert.tf
Include critical errors (with severity level 4) in alerting trigger.
```
[ ] Yes
[x] No
```
> Include critical errors in alerting trigger

- sprod.tfvars
Set max delivery counts in sprod to be the same as in prod
```
[ ] Yes
[x] No
```
> Set max delivery counts in sprod to be the same as in prod

- incomplete-envelopes-alert.tf
[daily alert for unprocessed envelopes](https://tools.hmcts.net/jira/browse/BPS-610)
Alert based on hmcts/bulk-scan-processor#631
```
[ ] Yes
[x] No
```
> Feature: new alert for incomplete envelopes

- README.md
- bin/create-case-worker.sh
- bin/create-user.sh
- bin/start-ccd-web.sh
- docker-compose.yml
- docker/ccd-definition-import/scripts/create-importer-user.sh
- docker/ccd-definition-import/scripts/upload-definition.sh
[Fix ccd docker for local testing](https://tools.hmcts.net/jira/browse/BPS-620)
https://github.com/hmcts/bulk-scan-shared-infrastructure/pull/103/commits/c3f9c793c96ff1b6f7b1f85221b6e3e698f483ab actually fixes the ccd importer container. Mainly focused to update idam as it was using old images
```
[ ] Yes
[x] No
```
> Update idam images

- main.tf
- storage-account.tf
-  Updated azure rm version to 1.22.1
- Working build in sandbox https://sandbox-build.platform.hmcts.net/job/HMCTS_Sandbox_Platform/job/bulk-scan-shared-infrastructure/job/UPDATE-AZURE-RM-VERSION/5/
```
[ ] Yes
[ x] No
```
> Fix shared infra -update azure rm version

- aat.tfvars
- app-gateway.tf
- demo.tfvars
- prod.tfvars
- saat.tfvars
- sandbox.tfvars
- sprod.tfvars
- variables.tf
- Working build on sandbox : https://sandbox-build.platform.hmcts.net/job/HMCTS_Sandbox_Platform/job/bulk-scan-shared-infrastructure/job/ADD-KEYVAULT-ID/3/console
```
[ ] Yes
[ x] No
```
> Remove azurerm_key_vault  resource and use vault id attribute for secret retrieval

- Jenkinsfile_CNP
-  Removed shared infra as it is deprecated
```
[ ] Yes
[ x] No
```
> Removed deprecated shared infra and used withinfra pipeline

- bin/start-specific-container.sh
- docker-compose.yml
Leftovers after migration to sidam
```
[ ] Yes
[x] No
```
> Fix scripts for local environment

- heartbeat-alert.tf
Send an email if orchestrator hasn't logged that it received the heartbeat message
> Add alert for heartbeat

- heartbeat-alert.tf
Increase the time so there is a change for 2 heartbeats to be delivered (heartbeats are sent every 10min)
> Change frequency and time window of the heartbeat alert

- key-vault.tf
- palo-alto.tf
- queue.tf
- Use master branch for key vault 
-  Use ref=master for queue and Palo Alto module to match tf approvals
```
[ ] Yes
[x ] No
```
> Fix terraform approval list matching issue

- aat.tfvars
- ithc.tfvars
- perftest.tfvars
- prod.tfvars
- sbox.tfvars
Assign managed identity object IDs to Key Vaults
```
[ ] Yes
[x] No
```
> Assign managed identity object IDs to Key Vaults

- Jenkinsfile_parameterized
> Remove deprecated pipeline

- queue.tf
https://tools.hmcts.net/jira/browse/BPS-886
```
[ ] Yes
[x] No
```
> Add unused config to notifications queue to fix the state file in aat

- sandbox.tfvars
- sbox.tfvars
Move managed identity object ID for sandbox to the right file
```
[ ] Yes
[x] No
```
> Move managed identity object ID for sandbox to the right file

- liveness-alert.tf
https://tools.hmcts.net/jira/browse/BPS-930
> Fix liveness alert for processor

- liveness-alert.tf
https://tools.hmcts.net/jira/browse/BPS-930
> Add liveness alert for payment processor

- liveness-alert.tf
https://tools.hmcts.net/jira/browse/BPS-933
> Use cloud_RoleName to identify apps for alerting

- no-envelopes-processed-alert.tf
In case empty result set is returned from the original query (before splitting into minutes using `make-series`) nothing gets calculated and outcome is 0 rows (false or not). Need to backfill with all this with zeros in order to make query working. Would only need 1 row present for `make-series` work but with custom `datatable` is not possible to call functions like `now()`
Ran this query in AppInsights. The response was as expected: `files_are_processed = false`
```
[ ] Yes
[x] No
```
> Upgrade "no envelopes processed" alert

- storage-account.tf
https://tools.hmcts.net/jira/browse/BPS-972
Add storage account connection string to key vault
```
[ ] Yes
[x] No
```
> Add storage account connection string to key vault

- app-gateway.tf
- This needs reverting as the allow-inbound-https-internal has invalid Address prefix.
- Alternatively fix can be applied PR for which is already open but we don't want to apply the fix now to prod as the test is pending with our supplier.
> Revert "Update app-gateway.tf"

- no-new-envelopes-alert.tf
https://tools.hmcts.net/jira/browse/BPS-985
> Add new no-new-envelopes alert

- storage-account.tf
https://tools.hmcts.net/jira/browse/BPS-1045
Create publiclaw container
```
[ ] Yes
[x] No
```
> Create publiclaw container

- payments-scheduled-jobs-alerts.tf
https://tools.hmcts.net/jira/browse/BPS-1263
Add alerts for payment processor scheduled task:
- PaymentMessageProcessTask
```
[ ] Yes
[x] No
```
> Add alert for the scheduled task in payment processor

- processor-scheduled-jobs-alert.tf
- processor-scheduled-jobs-alerts.tf
https://tools.hmcts.net/jira/browse/BPS-1263
Add alerts for the scheduled tasks in the processor.
Scheduled tasks: 
- blob processing 
- upload-documents 
- delete-rejected-files
- delete-complete-files
- send-orchestrator-notification
- incomplete-envelopes
```
[ ] Yes
[x] No
```
> Add alerts for the scheduled tasks in processor

- orchestrator-scheduled-jobs-alerts.tf
https://tools.hmcts.net/jira/browse/BPS-1263
Add alerts for the orchestrator scheduled tasks:
- EnvelopesQueueConsumeTask
- CleanupEnvelopesDlqTask
```
[ ] Yes
[x] No
```
> Add alerts for the scheduled tasks in orchestrator

- prod.tfvars
- queue.tf
- sprod.tfvars
- variables.tf
https://tools.hmcts.net/jira/browse/BPS-1099
```
[ ] Yes
[x] No
```
> Cleanup notifications queue infrastructure and the related secrets

- storage-account-staging.tf
- storage-account.tf
https://tools.hmcts.net/jira/browse/BPS-1301
add new container
```
[ ] Yes
[x] No
```
> add new container

- queue-staging.tf
- queue.tf
[Improve the way Service Bus clients are created](https://tools.hmcts.net/jira/browse/BPS-771)
1st step - introduce new secrets
```
[ ] Yes
[x] No
```
> Add shared access keys of all queues to vault

- app-gateway-nsg.tf
https://tools.hmcts.net/jira/browse/BPS-1027
- Configure NSG to allow AKS Clusters and Proxyout.
- Will test on lower environment before merging to PROD.
```
[ ] Yes
[ x] No
```
> Configured NSG rules for proxyout and aks cluster ips

- storage-account-staging.tf
- storage-account.tf
add required subnets for jenkins. Jenkins running in aks and to access storage accounts these subnets need to access storage accounts
```
[ ] Yes
[x] No
```
> add required subnets

- liveness-alert.tf
https://tools.hmcts.net/jira/browse/BPS-1347
Updated requests in line with changes in https://github.com/hmcts/reform-scan-shared-infra/pull/71 
Updated requests were tested in Azure portal prod with _success == "True"_
```
[ ] Yes
[x] No
```
> Update alert queries

- app-gateway-staging.tf
- palo-alto-staging.tf
> Jrjohnson87 patch 1

- Jenkinsfile_CNP
- storage-account.tf
add custom domain back to storage account
```
[ ] Yes
[x] No
```
> add custom domain back to storage account

- storage-account.tf
remove custom domain for storage for now
```
[ ] Yes
[x] No
```
> remove custom domain for storage for now

- storage-account-staging.tf
add staging account name back
```
[ ] Yes
[x] No
```
> add staging account name back

- queue.tf
try to fix queue param error
https://build.platform.hmcts.net/job/HMCTS_BSP/job/bulk-scan-shared-infrastructure/job/master/208/console
```
[ ] Yes
[x] No
```
> try to fix queue param error

- preview_vnet.tf
- provider.tf
- storage-account.tf
> add preview subnet for aat

- storage-account.tf
fix aat subnets
```
[ ] Yes
[x] No
```
> fix aat subnets

- key-vault.tf
- main.tf
change keyvault module branch to master
```
[ ] Yes
[x] No
```
> change keyvault module branch to master

- main.tf
add skip_provider_registration
```
[ ] Yes
[x] No
```
> add skip_provider_registration

- main.tf
skip_provider_registration = "true"
```
[ ] Yes
[x] No
```
> skip provider registration

- prod.tfvars
https://tools.hmcts.net/jira/browse/DTSBPS-412
increase max-retry count for payments queue for prod
```
[ ] Yes
[x] No
```
> increase max-retry count for payments queue for PROD

- dead-letter.tf
- payment-failure-alert.tf
https://tools.hmcts.net/jira/browse/DTSBPS-410
New custom event for payment failure
```
[ ] Yes
[ x] No
```
> DTSBPS-410: Alert for dead-letter exception

- dead-letter.tf
https://tools.hmcts.net/jira/browse/DTSBPS-443
Alert for dead-letter
```
[ ] Yes
[x ] No
```
> DTSBPS-410: Alert for dead-letter

- queue.tf
enable duplicate detection
```
[ ] Yes
[x] No
```
> enable duplicate detection

- payments-scheduled-jobs-alerts.tf
https://tools.hmcts.net/jira/browse/DTSBPS-647
adjust payment alert to new queue listener solution
```
[ ] Yes
[x] No
```
> DTSBPS-647 change payment alert

- orchestrator-scheduled-jobs-alerts.tf
https://tools.hmcts.net/jira/browse/DTSBPS-668
fix alert as queue consume design changed
```
[ ] Yes
[x] No
```
> DTSBPS-668 fix alert as design changed

- orchestrator-scheduled-jobs-alerts.tf
https://tools.hmcts.net/jira/browse/DTSBPS-668
change email alert according to new design
```
[ ] Yes
[x] No
```
> DTSBPS-668 change email alert according to new design

- orchestrator-scheduled-jobs-alerts.tf
https://tools.hmcts.net/jira/browse/DTSBPS-668
revert back the name to avoid delete alert
```
[ ] Yes
[x] No
```
> DTSBPS-668 revert back the name to avoid delete alert

- orchestrator-scheduled-jobs-alerts.tf
DTSBPS-668
DTSBPS-668 change time frame,
it should work every 1 hour and check last 63 minutes as job runs every 60 minutes?
```
[ ] Yes
[x] No
```
> DTSBPS-668 change time frame

- main.tf
- provider.tf
- state.tf
DTSBPS-722 fix terraform provider issue
```
[ ] Yes
[x] No
```
> DTSBPS-722 fix terraform provider issue

- data.tf
DTSPO-5016
```
[ ] Yes
[ ] No
```
> Add preview env

- preview_vnet.tf
fix preview name
```
[ ] Yes
[x] No
```
> fix preview name

- storage-account-staging.tf
- storage-account.tf
https://tools.hmcts.net/jira/browse/DTSBPS-836
```
[ ] Yes
[x] No
```
> Created privatelaw container

- storage-account-staging.tf
- storage-account.tf
Dtsbps 847 change nfd container
```
[ ] Yes
[ ] No
```
> Dtsbps 847 change nfd container

- data.tf
DTSBPS-856 fix network rules
```
[ ] Yes
[x] No
```
> DTSBPS-856 fix network rules

- cft_prod_vnet.tf
- provider.tf
- storage-account.tf
Adds new cft-prod-vnet subnets to production alongside the old core-prod-vnet subnet whitelisting
```
[ ] Yes
[ ] No
```
> Adds cft-prod-vnet subnets to prod alongside core-prod-vnet

- Jenkinsfile_CNP
remove halts
```
[ ] Yes
[x] No
```
> remove halts

- aat.tfvars
- alert_action_group.tf
- application-insights.tf
- data.tf
- dead-letter.tf
- demo.tfvars
- dlq-alert.tf
- exception-alert.tf
- heartbeat-alert.tf
- incomplete-envelopes-alert.tf
- ithc.tfvars
- key-vault.tf
- liveness-alert.tf
- main.tf
- no-new-envelopes-alert.tf
- orchestrator-scheduled-jobs-alerts.tf
- payments-scheduled-jobs-alerts.tf
- perftest.tfvars
- processor-scheduled-jobs-alerts.tf
- prod.tfvars
- provider.tf
- queue-staging.tf
- queue.tf
- sandbox.tfvars
- storage-account-staging.tf
- storage-account.tf
- variables.tf
https://github.com/hmcts/bulk-scan-shared-infrastructure/pull/254#discussion_r827773765
> DTSPO-4471 - fix terraform warnings

- queue-demo-premium.tf
- queue-premium.tf
- variables.tf
https://tools.hmcts.net/browse/DTSPO-4471
Adding premium tier service bus to bulk-scan
```
[ ] Yes
[ x ] No
```
> DTSPO-4471 - add premium servicebus

- queue-premium.tf
https://tools.hmcts.net/browse/DTSPO-4471
Capacity must be set to minimum of 1 for premium SKU
Also add missing zoneRedundant variable
```
[ ] Yes
[x] No
```
> DTSPO-4471 - add premium servicebus capacity

- dead-letter.tf
- dlq-alert.tf
- exception-alert.tf
- heartbeat-alert.tf
- incomplete-envelopes-alert.tf
- liveness-alert.tf
- no-new-envelopes-alert.tf
- orchestrator-scheduled-jobs-alerts.tf
- payments-scheduled-jobs-alerts.tf
- processor-scheduled-jobs-alerts.tf
- state.tf
[Tim Jacomb](https://app.slack.com/team/U02LNDGUUPL) [9:15 AM](https://hmcts-reform.slack.com/archives/CA4F2MAFR/p1648455310681389)
@here
For users of cnp-module-storage-account:
There’s been a breaking change in the upstream terraform provider, a field has been renamed:
allow_blob_public_access -> allow_nested_items_to_be_public
Please...you don’t actually enable it then you can just remove the variable as it defaults to false.
[GitHub search](https://cs.github.com/?scopeName=All+repos&scope=&q=org%3Ahmcts+allow_blob_public_access+-repo%3Ahmcts%2Fterraform-provider-azurerm)
See also the upgrade https://github.com/hmcts/cnp-module-storage-account/pull/24
```
[ ] Yes
[x] No
```
> upgrade azurerm provider

- storage-account-staging.tf
- storage-account.tf
Migration of storage accounts from LRS to ZRS
> DTSPO-5822 - ZRS Migration

- queue-premium.tf
- queue-staging.tf
- queue.tf
All changes have been merged to master now, so I'm reverting the branches back to master.
```
[ ] Yes
[x] No
```
> DTSPO-6371 - revert branches back to master

- catalog-info.yaml
Reverts hmcts/bulk-scan-shared-infrastructure#270
> Revert "Add backstage configuration file"

- application-insights.tf
https://tools.hmcts.net/jira/browse/DTSBPS-1071
Add appinsights connection string secret to bulk-scan keyvault
```
[ ] Yes
[x] No
```
> Add appinsights connection string to keyvault (DTSBPS-1071)

- data.tf
- storage-account.tf
Error: Error: Subnet: (Name "aks-00" / Virtual Network Name "core-prod-vnet" / Resource Group "aks-infra-prod-rg") was not found
```
[ ] Yes
[ x] No
```
> Remove old config post aks arm-tf

- queue-staging.tf
> adding staging queues for premium asb until sku is changed

- aat.tfvars
- demo.tfvars
- ithc.tfvars
- key-vault.tf
- perftest.tfvars
- prod.tfvars
- sandbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-15408
Now using https://github.com/hmcts/bulk-scan-shared-infrastructure/pull/273 MI
```
[ ] Yes
[ ] No
```
> Remove old MI references

- application-insights.tf
- liveness-alert.tf
- queue-premium.tf
- queue-staging.tf
- state.tf
https://tools.hmcts.net/jira/browse/FACT-2231
as title
```
[ ] Yes
[x] No
```
> FACT-2231 - Azurerm upgrade to 4.16.0

- storage-account-staging.tf
- storage-account.tf
> FACT-2181 removed ibca stuff

- Jenkinsfile_CNP
> FACT-1731 added branchestosync

- ithc.tfvars
- variables.tf
> changed location for app insights

- import.tf
https://tools.hmcts.net/jira/browse/DTSPO-26850
Added import block for 'bulk-scan-ithc-mi' Managed Identity
```
[ ] Yes
[X] No
```
> Added import block for Managed Identity

- application-insights-uk.tf
https://tools.hmcts.net/jira/browse/FACT-2133
Added new app insights
```
[ ] Yes
[x] No
```
> FACT-2133 Added new app insights
